### ISSUE TITLE
@ cannot be the first character of a line inside a code snippet

### ISSUE THREAD

**Issue by beatbits** [PolymerElements/iron-component-page#100]
### Description
The character '@' cannot be the first character of a line inside a code snippet.

example:
```css
‌@media (max-width: 768px) {
  .hiddenOnSmallScreen {
    display: none !important;
  }
}
```

### Expected outcome

the following text: 
‌@media (max-width: 768px) {
  .hiddenOnSmallScreen {
    display: none !important;
  }
}
coloured accordingly to the language.

### Actual outcome

```css

### Steps to reproduce

1. Putting a '@' as the first character inside a snippet code in your component documentation.
2. Enter in your web documentation.
3. See that your code snippet is not there.

### Browsers Affected
all browsers are affected

#### Workaround
You can skip this behaviour by putting the 'Zero-width non-joiner', (which is the following, embraced in brackets [ ]) before '@'.
